version: '3.8'

services:
  authoring-tool:
    build:
      context: ./01-authoring-tool
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  asset-search:
    build:
      context: ./02-asset-search
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  rag:
    build:
      context: ./03-rag
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - pgvector

  caption-api:
    build:
      context: ./05-caption-api
      dockerfile: Dockerfile
    ports:
      - "5009:5009"

  pgvector:
      environment:
          - POSTGRES_DB=ai
          - POSTGRES_USER=ai
          - POSTGRES_PASSWORD=ai
          - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
          - pgvolume:/var/lib/postgresql/data
      ports:
          - 5532:5432
      container_name: pgvector
      image: phidata/pgvector:16
volumes:
  pgvolume:
      external: true
      name: pgvolume
